# Generated by Django 5.1.6 on 2025-02-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('types', models.CharField(max_length=255)),
                ('abilities', models.CharField(max_length=255)),
                ('sprite', models.URLField()),
            ],
        ),
    ]
