# Generated by Django 6.0.4 on 2026-07-29 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100, unique=True)),
                ('power', models.PositiveSmallIntegerField(default=0)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('damage_class', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PokemonSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('types', models.JSONField(default=list)),
                ('abilities', models.JSONField(default=list)),
                ('sprite', models.URLField(blank=True)),
                ('stats', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('best_move', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strongest_for', to='pokedex.move')),
            ],
            options={
                'verbose_name': 'Pokemon species',
                'verbose_name_plural': 'Pokemon species',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_1', models.PositiveIntegerField()),
                ('score_2', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to=settings.AUTH_USER_MODEL)),
                ('species_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_first', to='pokedex.pokemonspecies')),
                ('species_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_second', to='pokedex.pokemonspecies')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_won', to='pokedex.pokemonspecies')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='pokedex_bat_user_id_bf6615_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='pokedex.pokemonspecies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_pokemon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saved Pokemon',
                'ordering': ('species__number',),
                'constraints': [models.UniqueConstraint(fields=('user', 'species'), name='unique_species_per_user')],
            },
        ),
    ]
