# Generated by Django 6.0.4 on 2026-07-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_migrate_pokemon_to_species'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pokemon',
            name='unique_pokemon_per_user_number',
        ),
        migrations.DeleteModel(
            name='Pokemon',
        ),
    ]
