# Generated by Django 6.0.4 on 2026-08-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_drop_legacy_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='turns_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='turns_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='candidate_moves',
            field=models.ManyToManyField(blank=True, related_name='candidate_for', to='pokedex.move'),
        ),
    ]
