# Generated by Django 6.0.4 on 2026-08-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_battle_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonspecies',
            name='artwork',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='artwork_shiny',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='sprite_shiny',
            field=models.URLField(blank=True),
        ),
    ]
