# Generated by Django 6.0.4 on 2026-08-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_shiny_sprites'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonspecies',
            name='base_experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='cry',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='height',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
