# Generated by Django 6.0.4 on 2026-08-07 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_pokedex_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='accuracy',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='move',
            name='self_ko',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='move',
            name='turn_cost',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='BattleGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.BigIntegerField()),
                ('player_hp', models.PositiveIntegerField()),
                ('opponent_hp', models.PositiveIntegerField()),
                ('player_max_hp', models.PositiveIntegerField()),
                ('opponent_max_hp', models.PositiveIntegerField()),
                ('turn_number', models.PositiveSmallIntegerField(default=0)),
                ('player_recharging', models.BooleanField(default=False)),
                ('opponent_recharging', models.BooleanField(default=False)),
                ('log', models.JSONField(default=list)),
                ('result', models.CharField(blank=True, max_length=10)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opponent_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_opponent', to='pokedex.pokemonspecies')),
                ('player_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player', to='pokedex.pokemonspecies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='pokedex_bat_user_id_c1b8c1_idx')],
            },
        ),
    ]
