# Generated by Django 6.0.4 on 2026-08-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0008_move_accuracy_move_self_ko_move_turn_cost_battlegame'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlegame',
            name='opponent_moves',
            field=models.ManyToManyField(blank=True, related_name='faced_in', to='pokedex.move'),
        ),
        migrations.AddField(
            model_name='battlegame',
            name='player_moves',
            field=models.ManyToManyField(blank=True, related_name='drafted_for', to='pokedex.move'),
        ),
    ]
